In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
#vocublary size  
voc_size = 1000 

In [6]:
#one hot representation 
one_hot_repr = [one_hot(words,voc_size) for words in sent ]


In [7]:
one_hot_repr

[[44, 832, 112, 439],
 [44, 832, 112, 23],
 [44, 386, 112, 676],
 [118, 79, 430, 653, 29],
 [118, 79, 430, 653, 906],
 [754, 44, 683, 112, 78],
 [810, 969, 881, 653]]

In [10]:
#word embedding representation 


from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [11]:
import numpy as np 

In [12]:
sent_length = 8 
embedding_docs = pad_sequences(one_hot_repr, padding= 'pre',maxlen=sent_length) 


In [13]:
print(embedding_docs)

[[  0   0   0   0  44 832 112 439]
 [  0   0   0   0  44 832 112  23]
 [  0   0   0   0  44 386 112 676]
 [  0   0   0 118  79 430 653  29]
 [  0   0   0 118  79 430 653 906]
 [  0   0   0 754  44 683 112  78]
 [  0   0   0   0 810 969 881 653]]


In [14]:
##feature representation 

dim = 10 

In [20]:
model = Sequential() 
model.add(Embedding(voc_size,dim,input_shape=(8,))) ## 8 == sent_length |
model.compile('adam','mse') ###adam is the optimizer 


C:\Users\sharm\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [21]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │        10,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,000 (39.06 KB)

 Trainable params: 10,000 (39.06 KB)

 Non-trainable params: 0 (0.00 B)